version: '1.0'
stages:
  - stage1
  - stage2
steps:
  logs_bombarding:
    stage: stage1
    title: free style step
    image: alpine
    commands:
     - echo "hello, world!"
   ${{STEP_NAME}}:
    stage: stage2
    title: ${{STEP_NAME}}
    image: alpine
    commands:
     - echo "hello, world!"
