version: '1.0'
stages:
  - stage1
  - stage2
steps:
  logs_bombarding:
    stage: stage1
    title: free style step
    image: alpine
    commands:
     - echo "hello, world!"
  step2:
    stage: stage2
    title: ${{STEP_NAME}}
    image: alpine
    scale:
      scale1:
        environment:
         - DATA=hello
      scale2:
        environment:
         - DATA=world
    commands:
     - echo $DATA
