version: '1.0'
stages:
  - stage1
  - launch
steps:
  logs_bombarding:
    stage: stage1
    title: free style step
    image: alpine
    commands:
     - echo "hello, world!"
     
  launch_composition:
    title: Launch Composition
    type: launch-composition
    composition:
      version: '2'
      services:
        app:
          image: nginx:latest
          ports:
          - 80
    environment_name: 'cf-nginx'
    stage: launch 
